share/.../generate-completions: Fail silently on very old pip
Some systems (e.g., Ubuntu 14.04) have a very old system pip without
`--disable-pip-version-check`. In this case we just generate no
completion because that's the easiest thing to do. If we actually want
to use pip enough on such a system that we'd want completion, we'd
also want to install our own user-local version of pip which would be
new enough to have this option.

diff --git a/share/bash-completion/generate-completions b/share/bash-completion/generate-completions
--- a/share/bash-completion/generate-completions
+++ b/share/bash-completion/generate-completions
@@ -31,15 +31,24 @@ generate_pip() {
         echo '# pip3 completion'
         #   Older versions of pip always set up completion for `pip`,
         #   even if run as `pip3`.
-        pip3 --disable-pip-version-check completion --bash \
-                | sed -e 's/pip$/pip3/'
+        pip3 2>/dev/null --disable-pip-version-check completion --bash \
+                | sed -e 's/pip$/pip3/' \
+                || { echo '# pip3 failed (no --disable-pip-version-check?)'
+                     #   This is rare; probably an old system pip3 on
+                     #   Ubuntu ≤ 14.04 or similar. Just ignore it; if we
+                     #   care we should install our own personal pip.
+                     return 0
+                   }
         #   Set up completion for `pip` even if it's not available by default
         #   because it becomes available when a virtualenv is activated.
         pip3 --disable-pip-version-check completion --bash \
                 | sed -e 's/pip3$/pip/'
     elif type pip >/dev/null 2>&1; then
         echo '# pip completion'
-        pip  --disable-pip-version-check completion --bash
+        pip  2>/dev/null --disable-pip-version-check completion --bash \
+            || { echo '# pip failed (no --disable-pip-version-check?)'
+                 return 0
+               }
     else
         echo '# pip3/pip not available'
     fi
